os:
  - linux
  - osx
  
osx_image: xcode61

before_install:
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && sudo add-apt-repository --yes ppa:beineri/opt-qt532
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && sudo apt-get update -qq
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && sudo apt-get install -qq qt53-meta-full libportmidi-dev libgecode-dev libxml2-dev libsndfile-dev portaudio19-dev libportmidi-dev
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && wget https://www.dropbox.com/s/e0o670ve6gv1dgt/cmake-3.0.2-Linux-x86_64.tar.gz?dl=1 -O cmake-3.0.2-Linux-x86_64.tar.gz
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && tar zxf cmake-3.0.2-Linux-x86_64.tar.gz
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && wget https://www.dropbox.com/s/exjazsh5epqet2g/gcc_4.9.1-1_amd64.deb?dl=1 -O gcc_4.9.1-1_amd64.deb
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && sudo dpkg -i gcc_4.9.1-1_amd64.deb

script:
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && export CMAKE_PATH="$(pwd)/cmake-3.0.2-Linux-x86_64/bin"
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && source /opt/qt53/bin/qt53-env.sh
- [[ "$TRAVIS_OS_NAME" = "linux" ]] && (PATH=$CMAKE_PATH:$PATH ./Build.sh jamoma iscore --clone)
- [[ "$TRAVIS_OS_NAME" = "osx" ]] && ./Build.sh jamoma iscore --clone --install-deps
